ALTER TABLE `hr_vacancy_experience` ADD COLUMN `exp_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`exp_id`);

ALTER TABLE `hr_user_experience` ADD COLUMN `exp_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`exp_id`);